### ISSUE TITLE
Hello, excuse me

### ISSUE THREAD

**Issue by h4rk8s** [woodyZootopia/nvim#2]
I come here from 'https://medium.datadriveninvestor.com/automatic-drummer-with-deep-learning-3e92723b5a79'

at you're old repo , "[https://gitlab.com/woodyZootopia/soundgame/-/issues/3](https://gitlab.com/woodyZootopia/soundgame/-/issues/3)"

but ,when I clone this repo then follow README.md, I can't run this repo , Can you help me ?

**Comment by swnakamura** [comment]
Oh, sorry! I somehow missed the notification so long.
If you were still struggling with that, I am glad to help you though.
